FIX: Tuple parsing for elixir
balance-platform/pillar pull request #63
Opened 2023-03-10 17:04 UTC by Zarathustra2

The added test would fail on the master branch with the following traceback:

```bash
  1) test data types tests Tuple test (PillarTest)
     test/pillar_test.exs:330
     ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Pillar.TypeConvert.ToElixir.convert/2

     The following arguments were given to anonymous fn/2 in Pillar.TypeConvert.ToElixir.convert/2:

         # 1
         {"UInt8", 1}

         # 2
         %{}

     code: assert {:ok, [%{"fst" => [1, 2], "snd" => [2, 3]}]} = Pillar.select(conn, sql)
     stacktrace:
       (pillar 0.35.0) lib/pillar/type_convert/to_elixir.ex:156: anonymous fn/2 in Pillar.TypeConvert.ToElixir.convert/2
       (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (pillar 0.35.0) lib/pillar/response_parser.ex:52: anonymous fn/2 in Pillar.ResponseParser.convert_row/2
       (elixir 1.14.3) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
       (stdlib 4.2) maps.erl:411: :maps.fold_1/3
       (elixir 1.14.3) lib/enum.ex:2480: Enum.map/2
       (pillar 0.35.0) lib/pillar/response_parser.ex:51: Pillar.ResponseParser.convert_row/2
       (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
       (pillar 0.35.0) lib/pillar/response_parser.ex:17: Pillar.ResponseParser.parse/1
       test/pillar_test.exs:333: (test)
```

I am not sure why it was accumulating the tuple key types in an map instead of a list, that seemed like a bug to me. Because given the tuple `(1,2)` and using the key types as the key in the map both would be having the same key `UInt8' and hence would override each other. 

So I replace it and used a list instead.

2023-03-12 10:42 UTC, sofakingworld commented
@Zarathustra2 Hi! Thanks for contribution, some tests are failing.

Would you check your fix on several clickhouses (21.1, 22.1, 23.1 for example)

![image](https://user-images.githubusercontent.com/15660128/224539518-06558e1e-e9fb-4d02-ac84-96bb39986244.png)

2023-03-12 10:50 UTC, sofakingworld requested changes

2023-03-12 10:50 UTC, sofakingworld commented on lib/pillar/type_convert/to_elixir.ex
> +    |> Enum.map(fn {key_type, value} ->
Backward capability needed for format of Clickhouse 23.1

2023-03-13 10:39 UTC, Zarathustra2 commented
can u rerun the CI @sofakingworld pls?

2023-03-14 11:37 UTC, Zarathustra2 commented
@sofakingworld 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/33396162/224988922-eeb11db4-6922-4f91-9f7f-7a50ebfd5f34.png">


This is the table & the data that gets inserted in the table in the test that fails. It has one column named `field` and and one row with a tuple of data `(4.5,5,'value')`. 

So I think the test case is actually wrong and my code is correct. 

So I think this code which seeds the data into the table is wrong:
```elixir
        assert {:ok, ""} =
                 Pillar.insert_to_table(conn, table_name, %{
                   "field" => {:json, test_json_map}
                 })
```

and needs to be corrected

2023-03-14 18:28 UTC, Zarathustra2 commented
Ah wait, I think i know the issue. Will push a fix later! :)

2023-03-14 22:27 UTC, Zarathustra2 commented
@sofakingworld I think I fixed it now. I am not sure why some of the CI steps have been cancelled

2023-03-15 11:42 UTC, sofakingworld commented
@Zarathustra2 
![image](https://user-images.githubusercontent.com/15660128/225298454-a87b17ab-a7f0-4ab9-a4a8-932ff9ea8742.png)

I'll merge soon and release new version will your PRs 👍🏻

2023-03-15 11:42 UTC, Zarathustra2 commented
nice awesome. Thanks for this library! @sofakingworld

2023-03-15 18:16 UTC, merged